config/routes.rb
Rails.application.routes.draw do
  devise_for :people

  root 'exegesis#index'

  get 'exegesis' => 'exegesis#index'
  get 'ledger' => 'ledger#index'
  get 'panopticon' => 'panopticon#index'

  post 'balance/send' => 'balance#send'
  post 'balance/settle' => 'balance#settle'

  devise_scope :person do
    get 'leave', to: 'devise/sessions#destroy'
  end

  resources :tags

  resources :events

  resources :people

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :person
  has_many :event_tags
  has_many :tags, through: :event_tags

  def to_s
    "Event \##{self.id}: Worked on #{self.tags.length} tags for #{self.hours} hours on #{self.date}"
  end
end

app/models/event_tag.rb
class EventTag < ActiveRecord::Base
  belongs_to :event
  belongs_to :tag
end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
  has_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :person
  belongs_to :tag_group
  has_many :event_tags
  has_many :events, through: :event_tags
  validates :name, presence: true
end

app/models/tag_group.rb
class TagGroup < ActiveRecord::Base
  belongs_to :person
  has_many :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/balance_controller.rb
class BalanceController < ApplicationController
  before_action :authenticate_person!

  def send
    # TODO: look these up in the database & track amounts there
    params[:sender]
    params[:receiver]

    @result = {
      :errors => false,
      :balance => params[:amount]
    }
  end

  def settle
    # TODO: look these up in the database & track amounts there
    params[:sender]
    params[:receiver]

    @result = {
        :errors => false,
        :balance => params[:amount]
    }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_person!
  before_action :set_event, only: [:show]

  # GET /events.json
  def index
    @events = Event.all.where(person_id: current_person.id).includes(:tags)
  end

  # POST /events.json
  def create
    @event = Event.new(event_params.merge({ person_id: current_person.id }))
    @event.tags = Tag.find(params[:tags])

    respond_to do |format|
      # TODO: For some reason, @event.save blows up here if any tags were passed in.
      if @event.save
        format.html { redirect_to @event, notice: 'Event successfully saved.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :hours, :tags)
    end
end

app/controllers/exegesis_controller.rb
class ExegesisController < ApplicationController
  before_action :authenticate_person!

  def index
    @month_names = %w(January February March April May June July August September October November December)

    @exegesis = {}
    # TODO: update this to work with tags instead of projects
    events = Event.joins('LEFT JOIN event_tags ON events.id=event_tags.event_id LEFT JOIN tags ON event_tags.tag_id=tags.id')
                  .where(person_id: current_person.id)
                  .select('SUM(hours) AS hours,
                           EXTRACT(MONTH FROM "date") AS "month",
                           EXTRACT(YEAR FROM "date") AS "year",
                           tags.id,
                           tags.name')
                  .group('"year", "month", tags.id')
    # There has got to be a more efficient way to do this loop.
    events.each do |event|
      year = event.year.to_i
      month = event.month.to_i
      @exegesis[year] = {} unless @exegesis.has_key? year
      @exegesis[year][month] = {} unless @exegesis[year].has_key? month
      @exegesis[year][month][event.id] = { name: event.name, hours: event.hours.to_i }
    end
  end
end

app/controllers/ledger_controller.rb
class LedgerController < ApplicationController
  before_action :authenticate_person!

  def index
    @tags = Tag.all.where(person_id: current_person.id)
    @events = Event.all.where(person_id: current_person.id).includes(:tags).order('date DESC')
  end
end

app/controllers/panopticon_controller.rb
class PanopticonController < ApplicationController
  before_action :authenticate_person!

  def index
    @tags = Tag.joins('LEFT JOIN tag_groups tg ON tags.tag_group_id=tg.id LEFT JOIN events_tags ON tags.id=events_tags.tag_id')
               .select('tags.*, tg.name AS tag_group_name, tg.description AS tag_group_description, COUNT(events_tags.event_id) AS event_count')
               .group('tags.id, tg.id')
               .where(person_id: current_person.id)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_person!

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :email)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_person!
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)
    @tag.archived = tag_params[:archived] || false
    @tag.person = current_person

    respond_to do |format|
      if @tag.save
        format.json { render :show, status: :created, location: @tag }
      else
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :archived)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/exegesis/index.html.erb
<div class="container exegesis">

<div class="row">
  <div class="col-md-12 text-center">
    <%= image_tag 'e.png' %>
  </div>
</div>

<% @exegesis.each do |year, months| %>
  <div class="row">
    <blockquote>
      <p class="lead">
        <%= year %>
      </p>
    </blockquote>
  </div>

  <% counter = 0 %>
  <% months.each do |month, tags| %>
    <% if counter % 4 == 0 then %>
      <div class="row">
    <% end %>
    <div class="col-md-3 box">
      <p class="lead"><%= @month_names[month] %></p>
      <% tags.values.each do |tag| %>
        <div class="row">
          <div class="col-md-6"><%= tag[:name] %></div>
          <div class="col-md-6 text-right"><%= tag[:hours] %></div>
        </div>
      <% end %>
    </div>
    <% if counter % 4 == 3 then %>
      </div>
    <% end %>
    <% counter += 1 %>
  <% end %>

<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="gossamer" lang="en">
<head>
  <title>Gossamer</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>

<%= yield %>

<% if person_signed_in? %>

  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li><a href="exegesis">Exegesis</a></li>
        <li><a href="ledger">Ledger</a></li>
        <li><a href="panopticon">Panopticon</a></li>
        <li><a href="people/leave">Leave</a></li>
      </ul>
    </div>
  </nav>

<% end %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
<script>
  $(function() {
    $('.multiselect').multiselect();
  });
</script>

</body>
</html>

app/views/ledger/index.html.erb
<div class="container ledger" ng-controller="ledger">

  <div class="row">
    <div class="col-md-12 text-center">
      <h1>ledger</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10 col-md-offset-1 text-center">
      <table class="table table-bordered">
        <thead>
          <tr>
            <td>
              <select class="multiselect form-control " multiple name="tags" ng-model="event.tags">
                <%= options_for_select(@tags.map { |t| [t.name, t.id]}) %>
              </select>
            </td>
            <td>
              <%= text_field_tag :hours, '', { class: 'form-control', placeholder: 'Hours', 'ng-model' => 'event.hours' } %>
            </td>
            <td>
              <input
                class="form-control"
                placeholder="Date (Optional)"
                ng-model="event.date"
                data-provide="datepicker"
                data-date-today-highlight="true"
                data-date-clear-btn="true"
                data-date-autoclose="true"
                data-date-format="yyyy-mm-dd"
                >
            </td>
            <td>
              <button class='btn btn-primary' ng-click="add_event()">Write Event</button>
            </td>
          </tr>
          <tr>
            <th>Tags</th>
            <th>Hours</th>
            <th>Start Time</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td>
                <h4>
                  <% event.tags.each_with_index do |tag, i| -%>
                    <%- next if !tag -%>
                    <span class="label label-default"><%= tag.name %></span>
                  <% end -%>
                </h4>
              </td>
              <td><%= event.hours %></td>
              <td><%= event.date %></td>
              <td>
                <button class="btn btn-default">Edit</button>
                <button class="btn btn-default">X</button>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/panopticon/index.html.erb
<div class="container panopticon" ng-controller="panopticon">

  <ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#tags" role="tab" data-toggle="tab">tags</a></li>
    <li><a href="#inscriptions" role="tab" data-toggle="tab">inscriptions</a></li>
    <li><a href="#archives" role="tab" data-toggle="tab">archives</a></li>
    <li><a href="#tempo" role="tab" data-toggle="tab">tempo</a></li>
  </ul>

  <br>

  <div class="tab-content">
    <div class="tab-pane active" id="tags">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <table class="table table-bordered text-center">
            <tr>
              <th>Tag</th>
              <th>Events</th>
              <th>Metatags</th>
            </tr>
            <% @tags.each do |tag| %>
              <tr>
                <td><%= tag[:name] %></td>
                <td><%= tag[:event_count] %></td>
                <td>
                    <span class="label <%= if tag[:is_project] then 'label-primary' else 'label-default' end %>">Project</span>
                </td>
                <td>
                  <button type="button" class="btn btn-default">Description</button>
                  <button type="button" class="btn btn-default">X</button>
                </td>
              </tr>
            <% end %>
            <tr>
              <td colspan=4>
                <button type="button" class="btn btn-primary" ng-click="add_tag()">add tag</button>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    <div class="tab-pane" id="inscriptions">
      TODO: inscriptions
    </div>
    <div class="tab-pane" id="archives">
      TODO: archives
    </div>
    <div class="tab-pane" id="tempo">
      TODO: tempo
    </div>
  </div>

</div>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.email %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>